const initialWorkouts = [
  {
    day: "Monday",
    exercise: "Low Incline Barbell Bench Press",
    link: "",
    reps: [
      { value: 20, reps: 20 },
      { multiplier: 0.43, reps: 5 },
      { multiplier: 0.61, reps: 3 },
      { multiplier: 0.84, reps: 2 },
      { multiplier: 0.93, reps: 1 },
      { multiplier: 1.02, reps: 10 },
      { multiplier: 1.02, reps: 8 },
    ],
    tips: ["Set bench to 15 degrees", "Arch lower back", "Keep feet flat"],
    oneRepMax: 102,
    adjustmentFactor: 1,
  },
  {
    day: "Monday",
    exercise: "Flat Dumbbell Press",
    link: "",
    reps: [
      { value: 20, reps: 15 },
      { multiplier: 1.125, reps: 12 },
      { multiplier: 1.25, reps: 10 },
      { multiplier: 1.375, reps: 8 },
    ],
    tips: ["Keep elbows at a 45-degree angle", "Use a neutral grip"],
    oneRepMax: 27.5,
    adjustmentFactor: 1,
  },
  {
    day: "Monday",
    exercise: "Dips",
    link: "",
    reps: [{ value: 0, reps: "Max" }],
    tips: ["Lean slightly forward", "Keep elbows close to body"],
    oneRepMax: 0,
    adjustmentFactor: 1,
  },
  {
    day: "Monday",
    exercise: "Standing 1-arm Dumbbell Lateral Raise",
    link: "",
    reps: [
      { multiplier: 1, reps: 15 },
      { multiplier: 1, reps: 15 },
      { multiplier: 1, reps: 15 },
    ],
    tips: ["Keep torso upright", "Lift dumbbell to shoulder height"],
    oneRepMax: 6,
    adjustmentFactor: 1,
  },
  {
    day: "Monday",
    exercise: "Dumbbell Posterior Delt Raise",
    link: "",
    reps: [
      { multiplier: 1, reps: 25 },
      { multiplier: 1, reps: 25 },
      { multiplier: 1, reps: 25 },
    ],
    tips: [
      "Bend over at hips",
      "Raise dumbbells to the side",
      "Squeeze shoulder blades",
    ],
    oneRepMax: 4,
    adjustmentFactor: 1,
  },
  {
    day: "Monday",
    exercise: "Cable Pushdowns",
    link: "",
    reps: [
      { multiplier: 1, reps: 30 },
      { multiplier: 1.33, reps: 20 },
      { multiplier: 1.67, reps: 15 },
      { multiplier: 2, reps: 10 },
    ],
    tips: ["Use dual straps", "Keep elbows close to body", "Fully extend arms"],
    oneRepMax: 30,
    adjustmentFactor: 1,
  },
  {
    day: "Tuesday",
    exercise: "Wide Grip Upper Back Pulldown",
    link: "",
    reps: [
      { multiplier: 1, reps: 10 },
      { multiplier: 1, reps: 10 },
    ],
    tips: ["Lean back slightly", "Pull bar to upper chest"],
    oneRepMax: 45,
    adjustmentFactor: 1,
  },
  {
    day: "Tuesday",
    exercise: "Neutral Grip Chin-up",
    link: "",
    reps: [{ value: 0, reps: "Max" }],
    tips: ["Use straps to avoid grip fatigue", "Keep body straight"],
    oneRepMax: 0,
    adjustmentFactor: 1,
  },
  {
    day: "Tuesday",
    exercise: "Moderate Grip Seated Row",
    link: "",
    reps: [
      { multiplier: 1, reps: 12 },
      { multiplier: 1.125, reps: 12 },
    ],
    tips: ["Use handles that allow elbow retraction", "Pull with elbows"],
    oneRepMax: 45,
    adjustmentFactor: 1,
  },
  {
    day: "Tuesday",
    exercise: "Bodyweight Inverted Row",
    link: "",
    reps: [{ value: 0, reps: "Max" }],
    tips: [
      "Keep body straight",
      "Pull chest to bar",
      "Squeeze shoulder blades",
    ],
    oneRepMax: 0,
    adjustmentFactor: 1,
  },
  {
    day: "Tuesday",
    exercise: "Stiff Leg DB Deadlift with Shrug",
    link: "",
    reps: [
      { multiplier: 1, reps: 25 },
      { multiplier: 1, reps: 25 },
    ],
    tips: ["Keep back straight", "Hinge at hips", "Perform a shrug at the top"],
    oneRepMax: 15,
    adjustmentFactor: 1,
  },
  {
    day: "Tuesday",
    exercise: "Alternating DB Curl",
    link: "",
    reps: [
      { multiplier: 1, reps: 15 },
      { multiplier: 1, reps: 15 },
    ],
    tips: ["Keep upper arm stationary", "Rotate palm up", "Squeeze at the top"],
    oneRepMax: 10,
    adjustmentFactor: 1,
  },
  {
    day: "Tuesday",
    exercise: "Alternating DB Hammer Curl",
    link: "",
    reps: [
      { multiplier: 1, reps: 20 },
      { multiplier: 1, reps: 20 },
    ],
    tips: ["Keep upper arm stationary", "Curl with a neutral grip"],
    oneRepMax: 8,
    adjustmentFactor: 1,
  },
  {
    day: "Tuesday",
    exercise: "Pronated Cable Curl",
    link: "",
    reps: [
      { multiplier: 1, reps: 15 },
      { multiplier: 1, reps: 15 },
    ],
    tips: ["Use a wavy bar", "Keep elbows close to body", "Squeeze at the top"],
    oneRepMax: 15,
    adjustmentFactor: 1,
  },
  {
    day: "Thursday",
    exercise: "Seated Leg Curls",
    link: "",
    reps: [
      { multiplier: 1, reps: 12 },
      { multiplier: 1.125, reps: 12 },
      { multiplier: 1.25, reps: 12 },
      { multiplier: 1.375, reps: 12 },
    ],
    tips: ["Keep feet flexed", "Avoid using momentum", "Squeeze at the bottom"],
    oneRepMax: 55,
    adjustmentFactor: 1,
  },
  {
    day: "Thursday",
    exercise: "ATG Split Squat",
    link: "",
    reps: [
      { value: 0, reps: 5 },
      { multiplier: 0.1, reps: 5 },
      { multiplier: 0.2, reps: 5 },
      { multiplier: 0.3, reps: 5 },
      { multiplier: 0.4, reps: 5 },
      { multiplier: 0.45, reps: 5 },
      { multiplier: 0.5, reps: 5 },
      { multiplier: 0.55, reps: 5 },
    ],
    tips: [
      "Elevate front foot",
      "Focus on knee bend",
      "Use dumbbells or barbell",
    ],
    oneRepMax: 55,
    adjustmentFactor: 1,
  },
  {
    day: "Thursday",
    exercise: "VMO Goblet Squat",
    link: "",
    reps: [
      { multiplier: 0.3, reps: 20 },
      { multiplier: 0.35, reps: 20 },
      { multiplier: 0.4, reps: 20 },
    ],
    tips: ["Keep heels elevated", "Hold dumbbell close to chest", "Squat low"],
    oneRepMax: 50,
    adjustmentFactor: 1,
  },
  {
    day: "Thursday",
    exercise: "Stiff Leg Barbell Deadlifts",
    link: "",
    reps: [
      { multiplier: 0.5, reps: 12 },
      { multiplier: 0.55, reps: 12 },
    ],
    tips: ["Keep back straight", "Hinge at hips", "Lower barbell below knees"],
    oneRepMax: 100,
    adjustmentFactor: 1,
  },
  {
    day: "Thursday",
    exercise: "Single Leg Calf Raise",
    link: "",
    reps: [
      { value: 0, reps: 10 },
      { value: 0, reps: 10 },
      { value: 0, reps: 10 },
      { value: 0, reps: 10 },
    ],
    tips: [
      "Hold onto something for balance",
      "Lower heel below step",
      "Squeeze at top",
    ],
    oneRepMax: 0,
    adjustmentFactor: 1,
  },
  {
    day: "Thursday",
    exercise: "Seated Calf Raises",
    link: "",
    reps: [
      { multiplier: 0.4, reps: 15 },
      { multiplier: 0.5, reps: 15 },
      { multiplier: 0.6, reps: 15 },
    ],
    tips: [
      "Keep feet flat on platform",
      "Lower heels below platform",
      "Squeeze at top",
    ],
    oneRepMax: 50,
    adjustmentFactor: 1,
  },
  {
    day: "Friday",
    exercise: "Low Incline Barbell Bench Press",
    link: "",
    reps: [
      { value: 20, reps: 20 },
      { multiplier: 0.43, reps: 5 },
      { multiplier: 0.61, reps: 3 },
      { multiplier: 0.84, reps: 2 },
      { multiplier: 0.93, reps: 1 },
      { multiplier: 1.02, reps: 10 },
      { multiplier: 1.02, reps: 8 },
    ],
    tips: ["Set bench to 15 degrees", "Arch lower back", "Keep feet flat"],
    oneRepMax: 102,
    adjustmentFactor: 1,
  },
  {
    day: "Friday",
    exercise: "Flat Dumbbell Press",
    link: "",
    reps: [
      { value: 20, reps: 15 },
      { multiplier: 1.125, reps: 12 },
      { multiplier: 1.25, reps: 10 },
      { multiplier: 1.375, reps: 8 },
    ],
    tips: ["Keep elbows at a 45-degree angle", "Use a neutral grip"],
    oneRepMax: 27.5,
    adjustmentFactor: 1,
  },
  {
    day: "Friday",
    exercise: "Dips",
    link: "",
    reps: [{ value: 0, reps: "Max" }],
    tips: ["Lean slightly forward", "Keep elbows close to body"],
    oneRepMax: 0,
    adjustmentFactor: 1,
  },
  {
    day: "Friday",
    exercise: "Standing 1-arm Dumbbell Lateral Raise",
    link: "",
    reps: [
      { multiplier: 1, reps: 15 },
      { multiplier: 1, reps: 15 },
      { multiplier: 1, reps: 15 },
    ],
    tips: ["Keep torso upright", "Lift dumbbell to shoulder height"],
    oneRepMax: 6,
    adjustmentFactor: 1,
  },
  {
    day: "Friday",
    exercise: "Dumbbell Posterior Delt Raise",
    link: "",
    reps: [
      { multiplier: 1, reps: 25 },
      { multiplier: 1, reps: 25 },
      { multiplier: 1, reps: 25 },
    ],
    tips: [
      "Bend over at hips",
      "Raise dumbbells to the side",
      "Squeeze shoulder blades",
    ],
    oneRepMax: 4,
    adjustmentFactor: 1,
  },
  {
    day: "Friday",
    exercise: "Cable Pushdowns",
    link: "",
    reps: [
      { multiplier: 1, reps: 30 },
      { multiplier: 1.33, reps: 20 },
      { multiplier: 1.67, reps: 15 },
      { multiplier: 2, reps: 10 },
    ],
    tips: ["Use dual straps", "Keep elbows close to body", "Fully extend arms"],
    oneRepMax: 30,
    adjustmentFactor: 1,
  },
];

export default initialWorkouts;
